export const CONSTANT = {
  btnComponent: 'Button Component',
  btnMixComponent: 'Mix Component',
  btnListComponent: 'List Component',
  btnAlertComponent: 'Alert',
  btnActionSheetComponent: 'Action Sheet',
  btnCardComponent: 'Card',
  btnCheckBoxComponent: 'Check Box',
  btnRadioComponent: 'Radio Button',
  btnChipComponent: 'Chip',
  btnContentComponent: 'Content',
  btnDataTimeComponent: 'Date & Time',
  btnFloatingComponent: 'Floating Button',
  btnModalComponent: 'Modal',
  btnMenuComponent: 'Menu',
  btnPopoverComponent: 'Popover',
  btnRefresherComponent: 'Refresher',
  btnProgressIndicatorComponent: 'Progress Indicators',
  btnSegmentComponent: 'Segment',
  btnSlideComponent: 'Slide',
  btnTabsComponent: 'Tabs',
  btnToastComponent: 'Toast',
  btnToggleComponent: 'Toggle',
  btnToolbarComponent: 'Toolbar',
  btnHeaderComponent: 'Header',
  btnGridComponent: 'Grid',
  btnIonSelectOption: 'Ion Select Option',
  labelRadio: 'Radio',
  labelMale:'Male',
  labelFemale:'Female',
  labelOther:'Other',

  registrationPage: {
    registration: 'Registration',
    registrationFirstName: 'First name',
    registrationLastName: 'Last name',
    registrationEmail: 'Email',
    registrationPassword: 'Password',
  }
};

